package com.aiinsight.model.enums;

public enum ArtifactType {
    CLARIFICATION_BRIEF,
    SOURCE_LIST,
    RESEARCH_PLAN,
    COMPETITOR_PROFILE,
    COMPETITIVE_MATRIX,
    SWOT_ANALYSIS,
    REPORT_DRAFT,
    REVIEW_FINDINGS,
    REPORT_REVISION,
    FINAL_REPORT
}
